### ISSUE TITLE
SECURITY: Plase make sure security related features can be set and have proper defaults

### ISSUE THREAD

**Issue by aeimer** [wiremind/wiremind-helm-charts#148]
Hi Guys,

I checked our cluster with `popeye` and we see some issues with this helm chart.
```
[POP-306] Container could be running as root user. Check SecurityContext/Image.
[POP-300] Using "default" ServiceAccount.
[POP-301] Connects to API Server? ServiceAccount token is mounted.
[POP-302] Pod could be running as root user. Check SecurityContext/Image.
```

I think it would be good to have the settings for
`serviceAccount.automountServiceAccountToken` and `securityContext` in place.

**Comment by desaintmartin** [comment]
PR accepted! Sane & safe defaults should indeed be the norm.

**Comment by aeimer** [comment]
@desaintmartin Seems like we need some changes on the dockerfile to get the correct rights?!
![image](https://user-images.githubusercontent.com/25035182/172628626-5debc8e0-9fa4-40d1-a1ed-a09ed0de5b50.png)
I'll publish my current state in a second.

**Comment by desaintmartin** [comment]
Solved: closing.
