### ISSUE TITLE
Provide securityContext at container level in values.yaml

### ISSUE THREAD

**Issue by shilpa-0** [wiremind/wiremind-helm-charts#228]
Currently, securityContext in values.yaml is only available at the pod level. 

Please provide containerSecurityContext (or any other appropriate name) in values.yaml to define security context at container level.

**Comment by desaintmartin** [comment]
Hello,
I am not sure which Chart you refer to. In any case, feel free to open a PR!

**Comment by desaintmartin** [comment]
Sure, PR accepted for this feature!

**Comment by shilpa-0** [comment]
Please review: https://github.com/wiremind/wiremind-helm-charts/pull/237

**Comment by desaintmartin** [comment]
Solved by https://github.com/wiremind/wiremind-helm-charts/pull/237, closing.
