### ISSUE TITLE
Remove versions from volumeClaimTemplates labels

### ISSUE THREAD

**Issue by aschmalfeld** [wiremind/wiremind-helm-charts#233]
I tried to install a new version of clamAv on our kubernetes cluster via the `helm upgrade --install` command while a previous version was already installed and got the following error : 

`Error: UPGRADE FAILED: release clamav failed, and has been rolled back due to atomic being set: cannot patch "clamav" with kind StatefulSet: StatefulSet.apps "clamav" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
helm.go:84: [debug] cannot patch "clamav" with kind StatefulSet: StatefulSet.apps "clamav" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden`

I believe the reason is that the labels in the volumeClaimTemplates of the StatefulSet contain the `appVersion` and the version of the helm chart. Those versions obviously change when the app or the chart get updated but volumeClaimTemplates in a StatefulSet are not allowed to be updated. 
I looked at other StatefulSets that we use and they don't have versions in the labels or no labels at all. 
This can of course be worked around by deleting the helm release and installing again but it would still be nice if it got fixed.

**Comment by desaintmartin** [comment]
Hello,
Indeed, this is a bad practice! I even reported it back myself a few years ago to the then-centralized charts repository: https://github.com/helm/charts/issues/7803, but https://github.com/wiremind/wiremind-helm-charts/pull/46 broke it and I never realized it. We still could have matchLabels (example: https://github.com/bitnami/charts/blob/cfbfe86992eb83aa39118222bb9b13c14febced9/bitnami/redis/templates/master/application.yaml#L498) which are immutable, and do a breaking change.

PR accepted!
