### ISSUE TITLE
ClamAV Image Moved to GHCR

### ISSUE THREAD

**Issue by wobo-mattmencel** [wiremind/wiremind-helm-charts#255]
As of a recent release (https://github.com/Mailu/Mailu/releases/tag/2.0.0), the mailu/clamav image is no longer available in DockerHub. It's moved to ghcr.io.

I tried just setting these in values.yaml as a workaround for the moment, but there are some additional changes needed to upgrade to 2.x.

``` yaml
image.repository: ghcr.io/mailu/clamav
image.tag: 2.0.4
```

https://mailu.io/2.0/releases.html#upgrading

**Comment by wobo-mattmencel** [comment]
`1.9.50` is in GHCR, so this worked for me.

```yaml
image.repository: ghcr.io.mailu/clamav
image.tag: 1.9.50
```

**Comment by maxime1907** [comment]
Thanks for the report, i have done it here:
- https://github.com/wiremind/wiremind-helm-charts/pull/258
