### ISSUE TITLE
Helm repository url is wrong at artifacthub.io

### ISSUE THREAD

**Issue by magmax** [wiremind/wiremind-helm-charts#26]
This issue is not really related to this repository, but for the project.

The information showed to install clamav in https://artifacthub.io/packages/helm/wiremind/clamav?modal=install shows an invalid url (https://wiremind.github.com/wiremind-helm-charts). It should be `.io` instead of `.com`:
![image](https://user-images.githubusercontent.com/584026/115371028-ee184b00-a1c9-11eb-9b7a-e00bb1c1e50b.png)

**Comment by desaintmartin** [comment]
Thanks! It should have been fixed a few days ago.
