### ISSUE TITLE
ClamAV image - switch to clamav/clamav?

### ISSUE THREAD

**Issue by dasrecht** [wiremind/wiremind-helm-charts#325]
Hi there

I'm using the helm chart to install ClamAV and saw that the Mailu Image is still on the 0.105 version of clamav which is EOL - https://blog.clamav.net/2023/07/2023-08-16-releases.html

As ClamAV publishes images that are well maintained, I wonder if there are considerations moving to [clamav/clamav](https://hub.docker.com/r/clamav/clamav/) images - I saw the [TODO entry in the values.yaml](https://github.com/wiremind/wiremind-helm-charts/blob/main/charts/clamav/values.yaml#L8) ;)

It looks like there's also an ongoing discussion about the ClamAV upgrade on mailu https://github.com/Mailu/Mailu/issues/2919
but I wonder if it's not just easier to try to switch to the official image directly.

**Comment by dasrecht** [comment]
Did some testing to see if the change over to clamav/clamav would work but ran into file permission issues. 

As Mailu is also discussing the change over to a newer version, I went ahead and started checking if the newer version could be backported. 

I still feel it would be better to use the official image of Clamav. But let's see which way gets more traction.

**Comment by desaintmartin** [comment]
I'd also like to only use official upstream images in order to reduce supply chain length. I have to admit that we did not have the time to perform the switch, but that would of course be an outstanding contribution!

**Comment by dasrecht** [comment]
For now mailu updated their images - didn't check if it was released yet.
Did some work on the default images but the upstream images seem to need a bit of work still. 
Will have a look if i can continue that work in the coming weeks

**Comment by dasrecht** [comment]
Ok things have been released: https://github.com/Mailu/Mailu/pkgs/container/clamav

Still thinking that using the upstream image would be a good step to remove the dependency as there might be some changes coming up on mailu, because it seems that the image will switch at some point to the debian base image instead of building a dedicated image

**Comment by dasrecht** [comment]
It looks like the only changes we'd need is regarding the user management and security policies

Mainly because with the current settings we can't write into `/run/clamav`

```
install: can't create directory '/run/clamav': Permission denied
```

**Comment by JoshuaJackson-jobvite** [comment]
So they add in two init scripts. Base image requires the root behaviors but https://github.com/Cisco-Talos/clamav-docker/blob/a31fd3e888fb8e55b111e10f57231253b8ab93be/clamav/1.3/alpine/Dockerfile#L122 the init-unpeivledged does nor. We likely can set the entry point and retest. It should work

**Comment by JoshuaJackson-jobvite** [comment]
So internal to Employ currently but testing has shown:

```Hi, 


The below args/command changes are working. 🙂

     containers:
       - args:
           - '"--user "clamav"'
         command:
           - /init-unprivileged
         image: 'clamav/clamav-debian:1.2.2'
```

So from a base level looks like there's a fairly straightforward way forward. Will work with the team's to submit a potential patch for this.
