### ISSUE TITLE
clamav failing with "install: can't create directory '/run/clamav': Permission denied"

### ISSUE THREAD

**Issue by Rakshithb1** [wiremind/wiremind-helm-charts#346]
Hello,

I'm experiencing the issue "install: can't create directory '/run/clamav': Permission denied"
 while using Clamav chart version 2.8.1 with the Clamav image "clamav/clamav:latest.
 kubernetes version: 1.26

I would like to know the difference between the official ClamAV image (clamav/clamav) and the mailu/clamav image.

**Comment by dasrecht** [comment]
This is a known issue - `clamav/clamav` is built quite differently - There's an ongoing [discussion](https://github.com/wiremind/wiremind-helm-charts/issues/325) to move towards `clamav/clamav` images but there are a few things that need to be considered. To the current state it's not drop-in replaceable.

**Comment by maxime1907** [comment]
We switched to the official image thanks to this PR:
- https://github.com/wiremind/wiremind-helm-charts/pull/456

Closing this since it should not be a problem anymore but feel free to re-open a new one if needed!
