### ISSUE TITLE
[karma] Upgrade Ingress definition as extensions/v1beta1 Ingress is deprecated

### ISSUE THREAD

**Issue by mavanier** [wiremind/wiremind-helm-charts#42]
When activating the ingress with the karma chart, the following warning is displayed.

Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

Could it be possible to update the Ingress manifest to use the networking.k8s.io/v1 definition?

I was unable to deploy in on OpenShift 4.7 I had to create one manually and turned Ingress off.

**Comment by desaintmartin** [comment]
Openshift 4.7 uses kubernetes 1.20 which still support this ingress version, so it is unlikely it is the root cause. However, PRs accepted!
