### ISSUE TITLE
mailu clamav image is no longer supported

### ISSUE THREAD

**Issue by arno4000** [wiremind/wiremind-helm-charts#432]
Apparently the mailu image of clamav is no longer supported, see https://github.com/Mailu/Mailu/issues/3160

**Comment by jplitza** [comment]
The [upstream image](https://hub.docker.com/r/clamav/clamav) can pretty much be used as a drop-in replacement. Only problem we have right now is with running it non-root, since this Helm chart doesn't support changing the entrypoint (to `/init-unprivileged`)
