### ISSUE TITLE
Impossible to Upgrade ClamAV Statefulset with Persistent Volume Claim

### ISSUE THREAD

**Issue by pinkfloydx33** [wiremind/wiremind-helm-charts#527]
By default, it is not possible to perform an upgrade of ClamAV when using a persistent volume. This is because the chart includes labels on the `volumeClaimTemplate` which incorporate the chart version information. The `volumeClaimTemplate` field (and it's children) cannot be updated once the StatefulSet has been created. 

>  StatefulSet.apps "clamav" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

This is caused by this:

https://github.com/wiremind/wiremind-helm-charts/blob/23dc111649e43db78e30e0f20d026522067d19f2/charts/clamav/templates/statefulset.yaml#L133-L138

The `clamav.labels` should be removed, trimmed down to exclude the version number, or be user-driven via the values file.

**Comment by maxime1907** [comment]
Hello, i have just fixed it with this this MR:
- https://github.com/wiremind/wiremind-helm-charts/commit/6857b755419968e2cd384df4dd7a1fe4b69b2ca6
