### ISSUE TITLE
Failed to deploy clamav chart with HPA memory

### ISSUE THREAD

**Issue by mblanloeil** [wiremind/wiremind-helm-charts#90]
I try to configure HPA with memory limits, but Chart is invalid due to values.schema.json 
https://github.com/wiremind/wiremind-helm-charts/blob/main/charts/clamav/values.schema.json#L216 

Both values are null and we have an error like : 
Error: values don't meet the specifications of the schema(s) in the following chart(s): clamav: - hpa.memory: Invalid type. Expected: null, given: string  

I deploy with argocd

**Comment by desaintmartin** [comment]
Indeed, schema is wrong here...
PR accepted!

**Comment by juris** [comment]
Looks like #227 now.

**Comment by desaintmartin** [comment]
For reference: https://github.com/wiremind/wiremind-helm-charts/pull/230 has been merged, but not the schema yet.
